sites:
  - name: kognise
    url: https://kognise.dev/
    colors:
      border: '#ced4da'
      text: '#000000'
      links: '#6741d9'
    stylesheets:
      - https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400&display=swap
    font_stack: '"IBM Plex Mono", monospace'
  - name: sugarfi
    url: https://sugarfi.dev/
    stylesheets:
      - https://sugarfi.dev/fonts.css
    font_stack: '"Free Pixel"'
  - name: arcade
    url: https://arcadewise.me/
    colors:
      border: '#268bd2'
      text: '#002b36'
      links: '#d33682'
    font_stack: serif
  # - name: piero
  #   url: https://piemadd.com/
  #   colors:
  #     border: '#131517'
  #     text: '#ffffff'
  #     links: '#468af0'
  #   stylesheets:
  #     - https://fonts.googleapis.com/css?family=Montserrat&display=swap
  #   font_stack: '"Montserrat", sans-serif' 
  - name: roylatgnail
    url: https://estrogens.rocks/
    font_stack: sans-serif
  - name: celeste
    url: https://celeste.exposed/
    stylesheets: 
      - https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap
      - https://celeste.exposed/embed.css
    font_stack: '"Libre Baskerville", serif'
  - name: skylar bleed
    url: https://murder.rocks/~skye/README.html
    font_size: 16px
  - name: ishan
    url: https://ishan.is-a.dev/
    colors:
      border: '#c9b697'
      text: '#000000'
      links: '#4d96c6'
    stylesheets:
      - https://fonts.googleapis.com/css?family=Nunito&display=swap
    font_stack: Futura, Nunito, Verdana, sans-serif 
  - name: perrypal
    url: https://perrypal.xyz/
    colors:
      border: 'transparent'
      text: '#ffffff'
      links: '#275a90'
    stylesheets:
      - https://fonts.googleapis.com/css?family=Quicksand&display=swap
    font_stack: Quicksand
  - name: hypnotic
    url: https://hypnoticsiege.net/
    colors:
      border: '#393e46'
      text: '#ffffff'
      links: '#3fa3eb'
  - name: wave
    url: https://wavecat.xyz/
    colors:
      border: '#6F6C94'
      text: '#ffffff'
      links: '#7BA1B5'
    stylesheets:
      - https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap
    font_stack: "Press Start 2P"
    font_size: 1em
  - name: khalby786
    url: https://khaleelgibran.com
    colors:
      border: '#575757'
      text: '#000000'
      links: '#5539cc'
    stylesheets:
      - https://fonts.googleapis.com/css2?family=Fira+Code&display=swap
    font_stack: "'Fira Code', monospace"
    font_size: 14px
  - name: munvoseli
    url: https://munvoseli.github.io/
    colors:
      border: '#112233'
      text: '#000000'
      links: '#445566'
    font_stack: 'monospace, sans-serif'

default_colors:
  border: '#000000'
  text: '#000000'
  links: '#0000ee'
